
# This file is generated by opta, do not modify it manually.
provider "aws" {
  region              = "ap-south-1"
  allowed_account_ids = ["992382730686"]

  default_tags {
    tags = {
      environment_name = "staging"
      region           = "ap-south-1"
      layer_name       = "df"
      service_name       = "df}"
    }
  }
}